on:
  push:
    branches:
    - main
    - features/**
    tags:
    - '*.*.*'
  pull_request:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # runs-on: [macOS-latest, ubuntu-latest, windows-latest]
        runs-on: [ windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - run: dotnet --info

    - if: matrix.runs-on == 'windows-latest' && github.ref != 'refs/heads/main' && !contains(github.ref, 'refs/tags/')
      run: ./build.ps1
    - if: (matrix.runs-on == 'windows-latest') && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
      run: |
        ./build.ps1
        dotnet nuget push .\nuget\*.nupkg -s https://nuget.pkg.github.com/DosSEdo/index.json -k 1a7dcb93a8f6668e293d582712b79e72dc0b7ae4 --skip-duplicate --no-symbols true
